# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fpga/project_fixed/project_fixed.srcs/sources_1/ip/mult_st_multiplier/mult_st_multiplier.xci
# IP: The module: 'mult_st_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga/project_fixed/project_fixed.srcs/sources_1/ip/mult_st_multiplier/mult_st_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_st_multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/fpga/project_fixed/project_fixed.srcs/sources_1/ip/mult_st_multiplier/mult_st_multiplier.xci
# IP: The module: 'mult_st_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fpga/project_fixed/project_fixed.srcs/sources_1/ip/mult_st_multiplier/mult_st_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_st_multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
